services:
  mychat-app:
    build: .
    container_name: mychat-app
    ports:
      - "${GRADIO_HOST_PORT:-7860}:${GRADIO_SERVER_PORT:-7860}"
    env_file:
      - .env
    environment:
      - GRADIO_SERVER_NAME
      - GRADIO_SERVER_PORT
    #volumes:
    #  - .:/app
    restart: unless-stopped 